apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mariemendoye/ml-frontend:latest
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: REACT_APP_BACKEND_URL
            - name: CHOKIDAR_USEPOLLING
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: CHOKIDAR_USEPOLLING
          ports:
            - containerPort: 3000
